/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq;


import dev.t3hw.mhn.db.jooq.tables.Posts;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>db</code>
     */
    public static final Db DB = new Db();

    /**
     * The table <code>db.posts</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Db() {
        super(DSL.name("db"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Posts.POSTS
        );
    }
}
