/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq;


import dev.t3hw.mhn.db.jooq.tables.Posts;
import dev.t3hw.mhn.db.jooq.tables.records.PostsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PostsRecord> CONSTRAINT_6 = Internal.createUniqueKey(Posts.POSTS, DSL.name("CONSTRAINT_6"), new TableField[] { Posts.POSTS.ID }, true);
}
