/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq;


import dev.t3hw.mhn.db.jooq.tables.Posts;


/**
 * Convenience access to all tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>db.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;
}
