/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Posts implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String content;
    private Integer votes;

    public Posts() {}

    public Posts(Posts value) {
        this.id = value.id;
        this.content = value.content;
        this.votes = value.votes;
    }

    public Posts(
        Long id,
        String content,
        Integer votes
    ) {
        this.id = id;
        this.content = content;
        this.votes = votes;
    }

    /**
     * Getter for <code>db.posts.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>db.posts.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>db.posts.content</code>.
     */
    @Size(max = 1000000000)
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>db.posts.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>db.posts.votes</code>.
     */
    public Integer getVotes() {
        return this.votes;
    }

    /**
     * Setter for <code>db.posts.votes</code>.
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Posts other = (Posts) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Posts (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(votes);

        sb.append(")");
        return sb.toString();
    }
}
