/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq.tables.daos;


import dev.t3hw.mhn.db.jooq.AbstractSpringDAOImpl;
import dev.t3hw.mhn.db.jooq.tables.Posts;
import dev.t3hw.mhn.db.jooq.tables.records.PostsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class PostsDao extends AbstractSpringDAOImpl<PostsRecord, dev.t3hw.mhn.db.jooq.tables.pojos.Posts, Long> {

    /**
     * Create a new PostsDao without any configuration
     */
    public PostsDao() {
        super(Posts.POSTS, dev.t3hw.mhn.db.jooq.tables.pojos.Posts.class);
    }

    /**
     * Create a new PostsDao with an attached configuration
     */
    @Autowired
    public PostsDao(Configuration configuration) {
        super(Posts.POSTS, dev.t3hw.mhn.db.jooq.tables.pojos.Posts.class, configuration);
    }

    @Override
    public Long getId(dev.t3hw.mhn.db.jooq.tables.pojos.Posts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Posts.POSTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchById(Long... values) {
        return fetch(Posts.POSTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public dev.t3hw.mhn.db.jooq.tables.pojos.Posts fetchOneById(Long value) {
        return fetchOne(Posts.POSTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchOptionalById(Long value) {
        return fetchOptional(Posts.POSTS.ID, value);
    }

    /**
     * Fetch records that have <code>content BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchRangeOfContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(Posts.POSTS.CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchByContent(String... values) {
        return fetch(Posts.POSTS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>votes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchRangeOfVotes(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Posts.POSTS.VOTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>votes IN (values)</code>
     */
    public List<dev.t3hw.mhn.db.jooq.tables.pojos.Posts> fetchByVotes(Integer... values) {
        return fetch(Posts.POSTS.VOTES, values);
    }
}
