/*
 * This file is generated by jOOQ.
 */
package dev.t3hw.mhn.db.jooq.tables.records;


import dev.t3hw.mhn.db.jooq.tables.Posts;

import jakarta.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PostsRecord extends UpdatableRecordImpl<PostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>db.posts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.posts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>db.posts.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.posts.content</code>.
     */
    @Size(max = 1000000000)
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.posts.votes</code>.
     */
    public void setVotes(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.posts.votes</code>.
     */
    public Integer getVotes() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostsRecord
     */
    public PostsRecord() {
        super(Posts.POSTS);
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(Long id, String content, Integer votes) {
        super(Posts.POSTS);

        setId(id);
        setContent(content);
        setVotes(votes);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(dev.t3hw.mhn.db.jooq.tables.pojos.Posts value) {
        super(Posts.POSTS);

        if (value != null) {
            setId(value.getId());
            setContent(value.getContent());
            setVotes(value.getVotes());
            resetTouchedOnNotNull();
        }
    }
}
