<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>dev.t3hw.mhn</groupId>
    <artifactId>mhn</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>openapi-spec</artifactId>

  <properties>
    <yaml-location-service>/src/main/resources/swagger/model.yaml</yaml-location-service>
    <spring-boot.repackage.skip>true</spring-boot.repackage.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>dev.t3hw.mhn</groupId>
      <artifactId>common</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>7.12.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${org.projectlombok.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-Amapstruct.verbose=true</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${org.projectlombok.version}</version>
            </path>
          </annotationProcessorPaths>
          <!-- <compilerArgs>
            <arg>-Amapstruct.verbose=true</arg>
          </compilerArgs> -->
        </configuration>
      </plugin>
      
      <!-- <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/src/main/java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/src/test/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin> -->

      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>Import-Server-Swagger</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <inputSpec>${project.basedir}${yaml-location-service}</inputSpec>
              <output>${project.build.directory}/generated-sources</output>
              <!-- <output>${project.basedir}</output> -->
              <generatorName>spring</generatorName>
              <apiPackage>dev.t3hw.mhn.server</apiPackage>
              <modelPackage>dev.t3hw.mhn.model</modelPackage>
              <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
              <configOptions>
                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                <delegatePattern>true</delegatePattern>
                <documentationProvider>springdoc</documentationProvider>
                <additionalModelTypeAnnotations>
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@Valid
                </additionalModelTypeAnnotations>
                <disallowAdditionalPropertiesIfNotPresent>true</disallowAdditionalPropertiesIfNotPresent>
                <openApiNullable>false</openApiNullable>
                <useOptional>true</useOptional>
                <useJakartaEe>true</useJakartaEe>
                <useSpringBoot3>true</useSpringBoot3>
                <generateApiTests>true</generateApiTests>
                <generateModelTests>true</generateModelTests>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>